- name: Add Users
  become: true
  user:
      name: "{{item.username}}"
      shell: /bin/bash
      createhome: yes
      comment: "{{item.comment}}"
      uid: "{{item.UID}}"
      group: "{{group}}"
      groups: "{{ item.groups }}"
      password: "{{item.password}}"
      home: /home/{{item.username}}
      update_password: on_create
      state: present
  with_items: "{{longstone_users}}"
