- name: Reboot systems
  become: true
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  notify: Wait for systems

- name: Wait for systems
  local_action: wait_for host={{ansible_ssh_host}} port=22 state=started delay=10
  become: false
